export const tableData = [
  {
    id: 1,
    title: "A Random Title 1",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 2,
    title: "B Random Title 2",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 3,
    title: "C Random Title 3",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 4,
    title: "D Random Title 4",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 5,
    title: "E Random Title 5",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 6,
    title: "F Random Title 6",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 7,
    title: "G Random Title 7",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 8,
    title: "H Random Title 8",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 9,
    title: "I Random Title 9",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 10,
    title: "J Random Title 10",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 11,
    title: "K Random Title 11",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 12,
    title: "L Random Title 12",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 13,
    title: "M Random Title 13",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 14,
    title: "N Random Title 14",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 15,
    title: "O Random Title 15",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 16,
    title: "P Random Title 16",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 17,
    title: "Q Random Title 17",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 18,
    title: "R Random Title 18",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 19,
    title: "S Random Title 19",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 20,
    title: "T Random Title 20",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 21,
    title: "U Random Title 21",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 22,
    title: "V Random Title 22",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 23,
    title: "W Random Title 23",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 24,
    title: "X Random Title 24",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 25,
    title: "Y Random Title 25",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 26,
    title: "Z Random Title 26",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 27,
    title: "AA Random Title 27",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
  {
    id: 28,
    title: "AB Random Title 28",
    language: "English",
    content_type: "video",
    version: "500",
    publish_stage: "3 Environment",
    workflow_stage: "Text For Chips",
    modified_at: "Dec 30, 2019 05:30",
    tags: "16 Tags",
    added: "Jan 5,2019",
    action: "Action",
  },
];
