export const tableData = [
  {
    id: 1,
    Title: "A Random Title 1",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 2,
    Title: "B Random Title 2",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 3,
    Title: "C Random Title 3",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 4,
    Title: "D Random Title 4",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 5,
    Title: "E Random Title 5",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 6,
    Title: "F Random Title 6",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 7,
    Title: "G Random Title 7",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 8,
    Title: "H Random Title 8",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 9,
    Title: "I Random Title 9",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 10,
    Title: "J Random Title 10",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 11,
    Title: "K Random Title 11",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 12,
    Title: "L Random Title 12",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 13,
    Title: "M Random Title 13",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 14,
    Title: "N Random Title 14",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 15,
    Title: "O Random Title 15",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 16,
    Title: "P Random Title 16",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 17,
    Title: "Q Random Title 17",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 18,
    Title: "R Random Title 18",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 19,
    Title: "S Random Title 19",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 20,
    Title: "T Random Title 20",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 21,
    Title: "U Random Title 21",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 22,
    Title: "V Random Title 22",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 23,
    Title: "W Random Title 23",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 24,
    Title: "X Random Title 24",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 25,
    Title: "Y Random Title 25",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 26,
    Title: "Z Random Title 26",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 27,
    Title: "AA Random Title 27",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
  {
    id: 28,
    Title: "AB Random Title 28",
    Language: "English",
    Content_Type: "video",
    Version: "500",
    Publish_Stage: "3 Environment",
    Workflow_Stage: "Text For Chips",
    Modified_At: "Dec 30, 2019 05:30",
    Tags: "16 Tags",
    Added: "Jan 5,2019",
    Action: "Action",
  },
];
